# Generated by Django 3.1.3 on 2020-11-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
