# Generated by Django 3.1.3 on 2020-11-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
